# Generated by Django 6.0.6 on 2026-07-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="工作日期")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="工时（小时）",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(blank=True, verbose_name="任务描述"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("development", "开发"),
                            ("testing", "测试"),
                            ("meeting", "会议"),
                            ("documentation", "文档"),
                            ("design", "设计"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "已完成"),
                            ("incomplete", "未完成"),
                            ("in_progress", "进行中"),
                            ("planned", "计划中"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="完成状态",
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        default=0,
                        help_text="0-100，正则匹配高分，模糊匹配低分，低于阈值的需人工审核",
                        verbose_name="置信度",
                    ),
                ),
                ("raw_text", models.TextField(blank=True, verbose_name="原始文本")),
                (
                    "is_categorized",
                    models.BooleanField(
                        default=False,
                        help_text="是否已分配到项目（未归类的项目为 null）",
                        verbose_name="已归类",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_entries",
                        to="accounts.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_entries",
                        to="projects.project",
                        verbose_name="关联项目",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entries",
                        to="reports.workreport",
                        verbose_name="来源日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "工时记录",
                "verbose_name_plural": "工时记录",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="stats_worke_employe_1159a7_idx",
                    ),
                    models.Index(
                        fields=["department", "date"],
                        name="stats_worke_departm_18a853_idx",
                    ),
                    models.Index(
                        fields=["project", "date"],
                        name="stats_worke_project_c6b195_idx",
                    ),
                    models.Index(
                        fields=["is_categorized"], name="stats_worke_is_cate_2b222e_idx"
                    ),
                ],
            },
        ),
    ]
