# Generated by Django 6.0.6 on 2026-07-01 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="项目名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="简短代号，如 'PROJ-A'",
                        max_length=50,
                        unique=True,
                        verbose_name="项目代号",
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        default=list,
                        help_text="日志文本中可能出现的其他名称，如 ['项目A', 'A项目', 'ProjA']",
                        verbose_name="别名列表",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "进行中"), ("archived", "已归档")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product_managers",
                    models.ManyToManyField(
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="产品经理",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["name"],
            },
        ),
    ]
