# Generated by Django 6.0.6 on 2026-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "系统管理员"),
                    ("dept_manager_l1", "一级部门管理"),
                    ("dept_manager_l2", "二级部门管理"),
                    ("project_manager", "项目经理"),
                    ("employee", "普通员工"),
                ],
                default="employee",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
