# Generated by Django 6.0.6 on 2026-07-02 05:54

from django.db import migrations

# Old → new role value mapping
ROLE_MAP = {
    "executive": "admin",
    "dept_manager": "dept_manager_l1",
    "product_manager": "project_manager",
}


def migrate_roles_forward(apps, schema_editor):
    """Map old role values to the new 5-role system."""
    User = apps.get_model("accounts", "User")
    for old, new in ROLE_MAP.items():
        updated = User.objects.filter(role=old).update(role=new)
        if updated:
            print(f"  Migrated {updated} user(s): {old} -> {new}")


def migrate_roles_backward(apps, schema_editor):
    """Reverse: map new roles back to old values."""
    User = apps.get_model("accounts", "User")
    REVERSE_MAP = {v: k for k, v in ROLE_MAP.items()}
    for new, old in REVERSE_MAP.items():
        updated = User.objects.filter(role=new).update(role=old)
        if updated:
            print(f"  Reverted {updated} user(s): {new} -> {old}")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_update_roles"),
    ]

    operations = [
        migrations.RunPython(
            migrate_roles_forward,
            reverse_code=migrate_roles_backward,
        ),
    ]
