# Generated by Django 6.0.6 on 2026-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("incremental", "增量同步"),
                            ("deep", "深度同步"),
                            ("full", "全量对账"),
                            ("manual", "手动触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "records_fetched",
                    models.IntegerField(default=0, verbose_name="获取记录数"),
                ),
                (
                    "records_parsed",
                    models.IntegerField(default=0, verbose_name="解析记录数"),
                ),
                (
                    "records_skipped",
                    models.IntegerField(default=0, verbose_name="跳过记录数"),
                ),
                (
                    "request_params",
                    models.JSONField(default=dict, verbose_name="请求参数"),
                ),
                (
                    "response_summary",
                    models.JSONField(default=dict, verbose_name="响应摘要"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "同步日志",
                "verbose_name_plural": "同步日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
