# Generated by Django 6.0.6 on 2026-07-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("dingtalk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "dingtalk_template_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="钉钉模板ID",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list,
                        help_text="模板字段列表，如 [{key: '今日完成工作', type: 'text'}, ...]",
                        verbose_name="字段定义",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "报告模板",
                "verbose_name_plural": "报告模板",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dingtalk_report_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="钉钉报告ID"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="报告日期")),
                (
                    "create_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="钉钉创建时间"
                    ),
                ),
                (
                    "raw_contents",
                    models.JSONField(
                        default=dict,
                        help_text="钉钉返回的原始 JSON，保留完整不可篡改",
                        verbose_name="原始内容",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("submitted", "已提交")],
                        default="submitted",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_reports",
                        to="accounts.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "sync_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="dingtalk.synclog",
                        verbose_name="同步批次",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="reports.reporttemplate",
                        verbose_name="模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作日志",
                "verbose_name_plural": "工作日志",
                "ordering": ["-report_date", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ReportContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_key", models.CharField(max_length=50, verbose_name="字段名")),
                ("field_value", models.TextField(blank=True, verbose_name="字段内容")),
                (
                    "extracted_entries",
                    models.JSONField(
                        default=list,
                        help_text="从该字段解析出的结构化条目列表",
                        verbose_name="提取条目",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="reports.workreport",
                        verbose_name="所属日志",
                    ),
                ),
            ],
            options={
                "verbose_name": "日志内容",
                "verbose_name_plural": "日志内容",
                "ordering": ["report", "order"],
            },
        ),
    ]
